version: '3.3'
services:
    mysql:
        container_name: cardsgo-mysql
        ports:
            - '3306:3306'
        network_mode: cardsgo
        volumes:
            - './database/.mysql/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD={password}
            - MYSQL_DATABASE=cardsgo
        image: 'mysql:8'
    cardsgo:
        container_name: cardsgo
        network_mode: cardsgo
        depends_on:
        - "mysql"
        image: cardsgo
    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - cardsgo
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        network_mode: cardsgo
        ports:
            - 80:80