version: '3.3'
services:
    mysql:
        container_name: cardsgo-mysql
        ports:
            - '3306:3306'
        network_mode: cardsgo
        volumes:
            - './database/.mysql/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD={password}
            - MYSQL_DATABASE=cardsgo
        image: 'mysql:8'
    cardsgo:
        container_name: cardsgo
        network_mode: cardsgo
        environment:
            - database_psw={password}
            - database_user=root
            - database_host=cardsgo-mysql
        depends_on:
        - "mysql"
        image: cardsgo
    certbot:
        container_name: certbot
        depends_on:
            - nginx
        image: certbot/certbot:latest
        volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
        command: certonly --webroot -w /var/www/certbot --force-renewal --email aleixo1lucas@gmail.com -d cardsgo.ddns.net --agree-tos
    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - cardsgo
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        network_mode: cardsgo
        ports:
            - 80:80
            - 443:443
    sonarqube:
        image: sonarqube:9.6.1-community
        container_name: sonarqube
        hostname: sonarqube
        ports:
        - 9000:9000
        environment:
        - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
        - sonar.jdbc.username=sonar
        - sonar.jdbc.password={password}
        volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
    db:
        image: postgres:13.1
        container_name: db
        hostname: db
        environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD={password}
        volumes:
        - pg_db:/var/lib/postgresql
        - pg_data:/var/lib/postgresql/data
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
volumes:
    pg_db:
        driver: local
    pg_data:
        driver: local
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data: